# Generated by Django 3.0.5 on 2021-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_asistencias_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='actividad',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='asistencias',
            name='observacion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
