# Generated by Django 3.0.5 on 2021-03-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_auto_20210311_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inasistencias',
            name='motivo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
