# Generated by Django 3.0.5 on 2021-03-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_auto_20210314_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inasistencias',
            name='justificativo',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
