# Generated by Django 3.0.5 on 2021-03-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0005_auto_20210315_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inasistencias',
            name='justificativo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
