# Generated by Django 3.0.5 on 2021-03-19 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_auto_20210319_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='dia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='asistencias',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='inasistencias',
            name='dia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inasistencias',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
