# Generated by Django 3.0.5 on 2021-03-19 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0007_auto_20210319_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 19, 13, 30, 43, 162188), null=True),
        ),
        migrations.AlterField(
            model_name='inasistencias',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 19, 13, 30, 43, 162689), null=True),
        ),
    ]
