# Generated by Django 3.0.5 on 2021-03-19 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0008_auto_20210319_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 19), null=True),
        ),
        migrations.AlterField(
            model_name='inasistencias',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 19), null=True),
        ),
    ]
