# Generated by Django 3.0.5 on 2021-03-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0009_auto_20210319_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencias',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inasistencias',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
