# Generated by Django 3.0.5 on 2021-04-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0010_auto_20210319_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='rol',
            field=models.CharField(blank=True, choices=[('Director(a)', 'Director(a)'), ('Encargado(a) del CBIT', 'Encargado(a) del CBIT')], max_length=30, null=True),
        ),
    ]
