# Generated by Django 3.0.5 on 2021-03-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0002_auto_20210306_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='descripcion',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='observacion',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
