# Generated by Django 3.0.5 on 2021-03-25 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0003_auto_20210322_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='empleado',
        ),
    ]
