# Generated by Django 3.0.5 on 2021-03-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBITS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(default='CBIT LA FUNDACION', max_length=25)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Empleados')),
            ],
            options={
                'db_table': 'cbits',
            },
        ),
        migrations.CreateModel(
            name='INTERNET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('linea_asociada', models.CharField(max_length=20)),
                ('tipo', models.CharField(blank=True, choices=[('EVDO', 'EVDO'), ('ABA', 'ABA'), ('SATELITAL', 'SATELITAL'), ('NINGUNO', 'NINGUNO')], max_length=15)),
            ],
            options={
                'db_table': 'internet',
            },
        ),
        migrations.CreateModel(
            name='Planteles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_DEA', models.CharField(default='OD06491504', max_length=15, unique=True)),
                ('matricula_est', models.PositiveIntegerField(default=200)),
                ('docentes', models.PositiveIntegerField(default=40)),
                ('nivel_academico', models.CharField(default='NIVEL Y BÁSICA', max_length=20)),
                ('dependencia', models.CharField(default='NACIONAL', max_length=10)),
                ('telefono', models.CharField(default='02343426661', max_length=15)),
                ('nombre_circuito', models.CharField(default='E.B.N LA FUNDACION', max_length=25)),
                ('anno_fundacion', models.IntegerField(default=1935)),
                ('cantidad_aulas', models.PositiveIntegerField(default=9)),
                ('cbit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estructura.CBITS')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativo.Empleados')),
            ],
            options={
                'db_table': 'planteles',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='MIRANDA', max_length=7)),
                ('municipio', models.CharField(default='BRION', max_length=5)),
                ('parroquia', models.CharField(default='TACARIGUA', max_length=9)),
                ('comuna', models.CharField(blank=True, max_length=15, null=True)),
                ('avenida', models.CharField(default='CARRETERA NACIONAL TACARIGUA', max_length=30)),
                ('sector', models.CharField(default='LA FUNDACION', max_length=13)),
                ('calle', models.CharField(default='AGRICOLA', max_length=9)),
                ('plantel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estructura.Planteles')),
            ],
        ),
        migrations.AddField(
            model_name='cbits',
            name='internet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estructura.INTERNET'),
        ),
    ]
