# Generated by Django 3.0.5 on 2021-03-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbits',
            name='internet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.INTERNET'),
        ),
    ]
