# Generated by Django 3.0.5 on 2021-03-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0002_auto_20210305_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbits',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
