# Generated by Django 3.0.5 on 2021-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0003_auto_20210321_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planteles',
            name='matricula_est',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
