# Generated by Django 3.0.5 on 2021-03-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0004_auto_20210322_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planteles',
            name='anno_fundacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planteles',
            name='cantidad_aulas',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planteles',
            name='docentes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planteles',
            name='nombre_circuito',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='planteles',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
