# Generated by Django 3.0.5 on 2021-03-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0010_auto_20210319_1934'),
        ('estructura', '0005_auto_20210322_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='plantel',
        ),
        migrations.RemoveField(
            model_name='planteles',
            name='cbit',
        ),
        migrations.AddField(
            model_name='cbits',
            name='plantel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Planteles'),
        ),
        migrations.AddField(
            model_name='planteles',
            name='direccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.Direccion'),
        ),
        migrations.AlterField(
            model_name='cbits',
            name='empleado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.Empleados'),
        ),
        migrations.AlterField(
            model_name='cbits',
            name='nombre',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='internet',
            name='linea_asociada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='internet',
            name='serial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='planteles',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.Empleados'),
        ),
    ]
