# Generated by Django 3.0.5 on 2021-03-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0006_auto_20210324_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='avenida',
            field=models.CharField(default='CARRETERA NACIONAL TACARIGUA', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='AGRICOLA', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='estado',
            field=models.CharField(default='MIRANDA', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='municipio',
            field=models.CharField(default='BRION', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='parroquia',
            field=models.CharField(default='TACARIGUA', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='sector',
            field=models.CharField(default='LA FUNDACION', max_length=13, null=True),
        ),
    ]
