# Generated by Django 3.0.5 on 2021-03-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20210324_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbits',
            name='codigo',
        ),
    ]
