# Generated by Django 3.0.5 on 2021-03-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0009_auto_20210325_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='comuna',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
