# Generated by Django 3.0.5 on 2021-04-06 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0010_auto_20210319_1934'),
        ('estructura', '0010_auto_20210325_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbits',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativo.Empleados'),
        ),
        migrations.AlterField(
            model_name='cbits',
            name='internet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estructura.INTERNET'),
        ),
        migrations.AlterField(
            model_name='cbits',
            name='plantel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estructura.Planteles'),
        ),
        migrations.AlterField(
            model_name='planteles',
            name='direccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estructura.Direccion'),
        ),
    ]
